// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OOADteam16CK.Models;

namespace OOADteam16CK.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20181212173103_Update2")]
    partial class Update2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OOADteam16CK.Models.Ban", b =>
                {
                    b.Property<int>("BanID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SoBan");

                    b.HasKey("BanID");

                    b.ToTable("Ban");
                });

            modelBuilder.Entity("OOADteam16CK.Models.ChiTietHd", b =>
                {
                    b.Property<int>("ChiTietHdID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DonGia");

                    b.Property<double>("GiamGia");

                    b.Property<int>("HoaDonID");

                    b.Property<int>("MonAnID");

                    b.Property<int>("SoLuong");

                    b.HasKey("ChiTietHdID");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("MonAnID");

                    b.ToTable("ChiTietHds");
                });

            modelBuilder.Entity("OOADteam16CK.Models.HoaDon", b =>
                {
                    b.Property<int>("HoaDonID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BanID");

                    b.Property<string>("ChuThich");

                    b.Property<int>("KhachHangID");

                    b.Property<int>("TrangThaiID");

                    b.HasKey("HoaDonID");

                    b.HasIndex("BanID");

                    b.HasIndex("KhachHangID");

                    b.HasIndex("TrangThaiID");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("OOADteam16CK.Models.KhachHang", b =>
                {
                    b.Property<int>("KhachHangID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Diem");

                    b.Property<string>("TenKh");

                    b.HasKey("KhachHangID");

                    b.ToTable("khachHangs");
                });

            modelBuilder.Entity("OOADteam16CK.Models.Loai", b =>
                {
                    b.Property<int>("LoaiID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MoTa");

                    b.Property<string>("TenLoai");

                    b.HasKey("LoaiID");

                    b.ToTable("Loais");
                });

            modelBuilder.Entity("OOADteam16CK.Models.LoaiKH", b =>
                {
                    b.Property<int>("LoaiKHID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenLoai");

                    b.HasKey("LoaiKHID");

                    b.ToTable("LoaiKHs");
                });

            modelBuilder.Entity("OOADteam16CK.Models.MonAn", b =>
                {
                    b.Property<int>("MonAnID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("DonGia");

                    b.Property<double>("GiamGia");

                    b.Property<string>("Hinh");

                    b.Property<int>("LoaiID");

                    b.Property<string>("MoTa");

                    b.Property<string>("TenMon");

                    b.Property<int>("TrangThaiID");

                    b.HasKey("MonAnID");

                    b.HasIndex("LoaiID");

                    b.HasIndex("TrangThaiID");

                    b.ToTable("MonAns");
                });

            modelBuilder.Entity("OOADteam16CK.Models.TrangThai", b =>
                {
                    b.Property<int>("TrangThaiID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenTrangThai");

                    b.HasKey("TrangThaiID");

                    b.ToTable("TrangThai");
                });

            modelBuilder.Entity("OOADteam16CK.Models.ChiTietHd", b =>
                {
                    b.HasOne("OOADteam16CK.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OOADteam16CK.Models.MonAn", "MonAn")
                        .WithMany()
                        .HasForeignKey("MonAnID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OOADteam16CK.Models.HoaDon", b =>
                {
                    b.HasOne("OOADteam16CK.Models.Ban", "Ban")
                        .WithMany()
                        .HasForeignKey("BanID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OOADteam16CK.Models.KhachHang", "KhanhHang")
                        .WithMany()
                        .HasForeignKey("KhachHangID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OOADteam16CK.Models.TrangThai", "TrangThai")
                        .WithMany()
                        .HasForeignKey("TrangThaiID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("OOADteam16CK.Models.MonAn", b =>
                {
                    b.HasOne("OOADteam16CK.Models.Loai", "Loai")
                        .WithMany()
                        .HasForeignKey("LoaiID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OOADteam16CK.Models.TrangThai", "TrangThai")
                        .WithMany()
                        .HasForeignKey("TrangThaiID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
